export const ADD_INVITEE = 'invitee/ADD_INVITEE';
export const REMOVE_INVITEE = 'invitee/REMOVE_INVITEE';
export const UPDATE_INVITEE = 'invitee/UPDATE_INVITEE';
export const TOGGLE_CONFIRM_INVITEE = 'invitee/TOGGLE_CONFIRM_INVITEE';
export const TOGGLE_ISEDITING_INVITEE = 'invitee/TOGGLE_ISEDITING_INVITEE';
export const UPDATE_PENDING_INVITEE = 'invitee/UPDATE_PENDING_INVITEE';
export const TOGGLE_FILTER_INVITEES = 'invitee/TOGGLE_FILTER_INVITEES';